language: csharp
dist: trusty
sudo: required

env:
- MONO_THREADS_PER_CPU=2000
mono:
- 4.0.5
os:
- linux
addons:
  apt:
    packages:
    - gettext
    - libcurl4-openssl-dev
    - libicu-dev
    - libssl-dev
    - libunwind8
    - zlib1g

solution: IrcDotNet.sln

install:
- curl -sSL https://raw.githubusercontent.com/aspnet/Home/dev/dnvminstall.sh | DNX_BRANCH=dev sh && source ~/.dnx/dnvm/dnvm.sh && dnvm install -r coreclr latest

script:
- dnu restore
- dnvm install -r mono latest
- dnu build source/IrcDotNet/ test/IrcDotNet.Test/
- cd test/IrcDotNet.Test/ && dnx IrcDotNet.Test
