<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>disable</Nullable>
    <AssemblyName>Meridian59.Net8Uv</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../../MobileClient/FlatAnchors.cs" Link="FlatAnchors.cs" />
    <ProjectReference Include="../../Meridian59/net8.csproj" />
  </ItemGroup>
</Project>
