<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyName>Meridian59</AssemblyName>
    <RootNamespace>Meridian59</RootNamespace>
    <DefineConstants>TRACE;ANYCPU;CONCURRENT</DefineConstants>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <EnableDefaultEmbeddedResourceItems>false</EnableDefaultEmbeddedResourceItems>
    <NoWarn>CS0618;CS0612;CS1591;SYSLIB0011</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="**/*.cs" Exclude="obj/**;bin/**" />
  </ItemGroup>
</Project>
